Repository AjinkyaSahu/Algorithms, pull requests merged in 2021-10, with the labels that each got.

#2 Interpolation search
  Interpolation Search/algo.txt
  Interpolation Search/psudocode.txt
  Linear Search Algo/algo.txt
  Linear Search Algo/psudocode.txt
Labels: hacktoberfest-2021, hacktoberfest-accepted

#4 Added A Queue Algorithm
  Algo - Tower of Hanoi/Algo.txt
  Algo - Tower of Hanoi/Pseudo_code.txt
  Algo -Queue/Algo.txt
  Algo -Queue/Pseudo_Code.txt
Labels: hacktoberfest-2021, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: documentation, hacktoberfest-2021, hacktoberfest-accepted

#6 Create BinarySearch.py
  BindarySearch/BinarySearch.py
Labels: good first issue, hacktoberfest-2021, hacktoberfest-accepted

#7 added searching algorithms
  Searching/binarySearch.cpp
  Searching/exponentialSearch.cpp
  Searching/interpolationSearch.cpp
  Searching/jumpSearch.cpp
  Searching/linearSearch.cpp
Labels: good first issue, hacktoberfest-2021, hacktoberfest-accepted

#8 added Djikstra's algorithm for shortest path
  Dijkstra's Shortest Path Algorithm/dijkstra'sAlgorithm.cpp
Labels: hacktoberfest-2021, hacktoberfest-accepted

#9 Created euclidean algorithm file
  Euclid's Algorithm/algo.cpp
Labels: hacktoberfest-2021, hacktoberfest-accepted

#10 Merge sort added
  Sorting/Merge_sort.c
Labels: hacktoberfest-2021, hacktoberfest-accepted
